server {
    ## SSL configuration pour ipv 4 
    listen 443 ssl;
    ## SSL configuration pour ipv 6
    listen [::]:443 ssl;
    ## Nom de domaine
    server_name tlecuyer.42.fr;

    ## Emplacement des fichier SSL necessaire pour le HTTPS
    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
    ##liste des protocoles SSL autorisés à être utilisés
    ssl_protocols TLSv1.2 TLSv1.3;


    ##Emplacement des fichiers sotckes dnas le volumes partagé avec wordpress 
    root /var/www/html/wordpress;
    ##Fichier d'index par défaut si la requete ne spécifie pas de fichier -> d'abord index.php, puis index.html
    index index.php index.html;

    ##pour toutes les requetes, trouve un fichier correspondant à l'URI demandé. Si aucun fichier n'est trouvé cherche dans dossier sinon 404 Not Found.
    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
    }
}
