services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    restart: always

env_files:
  - .env
networks:
  inception:
    driver: bridge

mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    networks:
      - inception
    env_file:
      - .env
    restart: always