events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;

        location /static/ {
            alias /var/www/html/;
            try_files $uri $uri/ =404;
        }
    }
}