FROM debian:bullseye

RUN apt-get update && apt-get install -y nginx openssl

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
-keyout /etc/ssl/private/nginx-selfsigned.key \
-out /etc/ssl/certs/nginx-selfsigned.crt \
-subj "/C=FR/L=PARIS/O=42/OU=student/CN=login.42.fr"

COPY conf/nginx.conf /etc/nginx/conf.d/default.conf 

CMD ["nginx", "-g", "daemon off;"]